name: Deploy to prod
on: workflow_call

# Это лишь примерные степы, как может выглядеть пайплайн, тк нет доступа к коду
jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy backend to prod
        run: echo Происходит деплой бэкенда

  deploy-frontend:
    needs: deploy-backend
    runs-on: ubuntu-latest
    steps:
      - name: Deploy frontend to prod
        run: echo Просиходит деплой фронтенда